Repository DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg, pull requests merged in 2023-07, with the labels that each got.

#1 Create .gitattributes
  .gitattributes
Labels: ✨ Feature

#3 Create Feature_template.md
  .github/ISSUE_TEMPLATE/Feature_template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚒️ Project

#9 Update ContentView.swift
  DreamEgg/DreamEgg/ContentView.swift
Labels: ⚒️ Project

#18 Feat/#10 feat mapview object animation
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/Assets.xcassets/beenzinoBreathIn.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/beenzinoBreathIn.imageset/beenzinoBreathIn.jpeg
  DreamEgg/DreamEgg/Assets.xcassets/beenzinoBreathOut.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/beenzinoBreathOut.imageset/beenzinoBreathOut.jpeg
  DreamEgg/DreamEgg/Stores/MapViewStore.swift
  DreamEgg/DreamEgg/Views/MapTestView.swift
Labels: ✨ Feature

#14 Feat/#8 feat local notifications
  .gitignore
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/Stores/LocalNotificationStore.swift
  DreamEgg/DreamEgg/Views/LocalNotificationView.swift
Labels: ✨ Feature

#19 Feat/#12 coredata sleep time crud
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/DreamEgg.xcdatamodeld/DreamEgg.xcdatamodel/contents
  DreamEgg/DreamEgg/Models/CoreDataContainer.swift
  DreamEgg/DreamEgg/Models/UserSleepTime.swift
  DreamEgg/DreamEgg/Stores/CoreDataStore.swift
  DreamEgg/DreamEgg/Stores/DailySleepTimeStore.swift
  DreamEgg/DreamEgg/Views/TestViews/CoreDataTestView.swift
Labels: ✨ Feature

#20 Feat/#15 app icon
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/Assets.xcassets/AppIcon.appiconset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/AppIcon.appiconset/Icon-App-iTunes@1x.png
  DreamEgg/DreamEgg/Assets.xcassets/AppIcon.appiconset/Icon_114×114@1x.png
  DreamEgg/DreamEgg/Assets.xcassets/AppIcon.appiconset/Icon_120x120@1x.png
  DreamEgg/DreamEgg/Assets.xcassets/AppIcon.appiconset/Icon_120×120@1x.png
  DreamEgg/DreamEgg/Assets.xcassets/AppIcon.appiconset/Icon_128x128@1x.png
  DreamEgg/DreamEgg/Assets.xcassets/AppIcon.appiconset/Icon_136x136@1x.png
  DreamEgg/DreamEgg/Assets.xcassets/AppIcon.appiconset/Icon_152x152@1x.png
  DreamEgg/DreamEgg/Assets.xcassets/AppIcon.appiconset/Icon_167x167@1x.png
  DreamEgg/DreamEgg/Assets.xcassets/AppIcon.appiconset/Icon_180×180@1x.png
  DreamEgg/DreamEgg/Assets.xcassets/AppIcon.appiconset/Icon_192×192@1x.png
  DreamEgg/DreamEgg/Assets.xcassets/AppIcon.appiconset/Icon_40x40@1x.png
  DreamEgg/DreamEgg/Assets.xcassets/AppIcon.appiconset/Icon_58x58@1x.png
  DreamEgg/DreamEgg/Assets.xcassets/AppIcon.appiconset/Icon_60×60@1x.png
  DreamEgg/DreamEgg/Assets.xcassets/AppIcon.appiconset/Icon_76x76@1x.png
  DreamEgg/DreamEgg/Assets.xcassets/AppIcon.appiconset/Icon_80x80@1x.png
  DreamEgg/DreamEgg/Assets.xcassets/AppIcon.appiconset/Icon_87×87@1x.png
Labels: 🎨 Design

#27 Feat/#24 color palette init
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/Extensions/Color+Palette.swift
Labels: ✨ Feature, 🎨 Design

#28 [Update/#24] characterFaceBackground Color Updated
  DreamEgg/DreamEgg/Extensions/Color+Palette.swift
Labels: 🎨 Design

#21 Feat/#13 feat timer
  .DS_Store
  DreamEgg/.DS_Store
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/DreamEggApp.swift
  DreamEgg/DreamEgg/Views/.DS_Store
  DreamEgg/DreamEgg/Views/MainEggsView.swift
  DreamEgg/DreamEgg/Views/SleepTimeSettingView.swift
Labels: ✨ Feature

#34 Feat/#31 decalendar implement
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/DreamEggApp.swift
  DreamEgg/DreamEgg/Extensions/Calendar+Weekdays.swift
  DreamEgg/DreamEgg/Extensions/Date+StartDates.swift
  DreamEgg/DreamEgg/Extensions/Date+Utilities.swift
  DreamEgg/DreamEgg/Extensions/DateFormatter+init.swift
  DreamEgg/DreamEgg/Views/Components/DECalendar.swift
  DreamEgg/DreamEgg/Views/TestViews/DECalendarTestView.swift
Labels: ✨ Feature

#26 Feat/#22 haptic feedback
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/Models/HapticManager.swift
  DreamEgg/DreamEgg/Views/TestViews/HapticFeedbackTestView.swift
Labels: ✨ Feature

#35 Feat/#11 animation gradient background
  .DS_Store
  DreamEgg/.DS_Store
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/Views/GradientBackgroundView.swift
Labels: ✨ Feature

#37 Feat/#16 feat egg gesture animation interaction
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/Assets.xcassets/BinyEgg.imageset/BinyEgg.svg
  DreamEgg/DreamEgg/Assets.xcassets/BinyEgg.imageset/Contents.json
  DreamEgg/DreamEgg/Stores/EggInteractionStore.swift
  DreamEgg/DreamEgg/Stores/EggInteractionStores.swift
  DreamEgg/DreamEgg/Views/EggInteractionTestView.swift
Labels: ✨ Feature

#39 Feat/#25 customizing time picker
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/Models/TimePickerModel.swift
  DreamEgg/DreamEgg/Views/Components/DETimePicker.swift
  DreamEgg/DreamEgg/Views/TestViews/TimePickerTestView.swift
Labels: ✨ Feature

#48 Feat/#46 refactoring timepicker structure
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/Models/TimePickerModel.swift
  DreamEgg/DreamEgg/Stores/TimePickerStore.swift
  DreamEgg/DreamEgg/Views/TestViews/TimePickerTestView.swift
  DreamEgg/DreamEgg/Views/TimePickerView.swift
Labels: ✨ Feature

#42 Feat/#33 drawing gesture of egg
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/Assets.xcassets/emptyEgg.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/emptyEgg.imageset/emptyEgg.svg
  DreamEgg/DreamEgg/DreamEggApp.swift
  DreamEgg/DreamEgg/Stores/EggAnimationStore.swift
  DreamEgg/DreamEgg/Stores/EggDrawStore.swift
  DreamEgg/DreamEgg/Stores/EggInteractionStore.swift
  DreamEgg/DreamEgg/Views/EggInteractionTestView.swift
  DreamEgg/DreamEgg/Views/TestViews/EggInteractionTestView.swift
Labels: ✨ Feature

#43 Feat/#36 ut ver layout
  .DS_Store
  .gitignore
  DreamEgg/.DS_Store
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/Assets.xcassets/DECurtain.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/DECurtain.imageset/DECurtain.png
  DreamEgg/DreamEgg/Assets.xcassets/DreamEggIcon.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/DreamEggIcon.imageset/DreamEggIcon.png
  DreamEgg/DreamEgg/Assets.xcassets/DreamWorldMap.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/DreamWorldMap.imageset/DreamWorldMap.svg
  DreamEgg/DreamEgg/Assets.xcassets/Dreampets/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Dreampets/Quakka_a.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Dreampets/Quakka_a.imageset/Quakka_a.svg
  DreamEgg/DreamEgg/Assets.xcassets/Dreampets/Quakka_b.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Dreampets/Quakka_b.imageset/Quakka_b.svg
  DreamEgg/DreamEgg/Assets.xcassets/Dreampets/Quokka_Face.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Dreampets/Quokka_Face.imageset/Quokka_Face.svg
  DreamEgg/DreamEgg/Assets.xcassets/Dreampets/Rabbit_a.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Dreampets/Rabbit_a.imageset/Rabbit_a.svg
  DreamEgg/DreamEgg/Assets.xcassets/FerretEgg.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/FerretEgg.imageset/FerretEgg.svg
  DreamEgg/DreamEgg/Assets.xcassets/Icons/CalendarIcon.imageset/CalendarIcon.png
  DreamEgg/DreamEgg/Assets.xcassets/Icons/CalendarIcon.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Icons/CalendarTabIcon.imageset/CalendarTabIcon.png
  DreamEgg/DreamEgg/Assets.xcassets/Icons/CalendarTabIcon.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Icons/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Icons/DreamEggTabIcon.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Icons/DreamEggTabIcon.imageset/DreamEggTabIcon.png
  DreamEgg/DreamEgg/Assets.xcassets/Icons/DreamWorldIcon.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Icons/DreamWorldIcon.imageset/DreamWorldIcon.png
  DreamEgg/DreamEgg/Assets.xcassets/Icons/DreamWorldTabIcon.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Icons/DreamWorldTabIcon.imageset/DreamWorldTabIcon.png
  DreamEgg/DreamEgg/Assets.xcassets/test.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/test.imageset/test.svg
  DreamEgg/DreamEgg/DreamEggApp.swift
  DreamEgg/DreamEgg/Extensions/Font+DosIyagi.swift
  DreamEgg/DreamEgg/Views/.DS_Store
  DreamEgg/DreamEgg/Views/Components/DECalendar.swift
  DreamEgg/DreamEgg/Views/Components/DETitleHeader.swift
  DreamEgg/DreamEgg/Views/Components/GradientBackgroundView.swift
  DreamEgg/DreamEgg/Views/ContentView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiAwakeView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiCreatureNamingView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiCurtainView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiDreamWorldView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiMainEggView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiNameConfirmView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiSleepGuideView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiTextCustomView.swift
  DreamEgg/DreamEgg/Views/TestViews/DECalendarTestView.swift
  DreamEgg/DreamEgg/Views/TestViews/LocalNotificationView.swift
  DreamEgg/DreamEgg/Views/TestViews/MainEggsView.swift
  DreamEgg/DreamEgg/Views/TestViews/MapTestView.swift
  DreamEgg/DreamEgg/Views/TestViews/SleepTimeSettingView.swift
Labels: ✨ Feature

#51 [Fix] project directory issue fixed
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg.xcodeproj/xcshareddata/xcschemes/DreamEgg.xcscheme
Labels: ⚒️ Project

#50 Feat/#45 ut ver logic implemented
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/DreamEgg.xcdatamodeld/DreamEgg.xcdatamodel/contents
  DreamEgg/DreamEgg/DreamEggApp.swift
  DreamEgg/DreamEgg/Extensions/Calendar+Weekdays.swift
  DreamEgg/DreamEgg/Extensions/Date+Utilities.swift
  DreamEgg/DreamEgg/Models/CoreDataContainer.swift
  DreamEgg/DreamEgg/Models/DENavigationManager.swift
  DreamEgg/DreamEgg/Resources/Constants.swift
  DreamEgg/DreamEgg/Stores/CoreDataStore+CRUD.swift
  DreamEgg/DreamEgg/Stores/CoreDataStore.swift
  DreamEgg/DreamEgg/Stores/DailySleepTimeStore.swift
  DreamEgg/DreamEgg/Stores/EggInteractionStores.swift
  DreamEgg/DreamEgg/Stores/Interface/CoreDataRepresentable.swift
  DreamEgg/DreamEgg/Stores/TimePickerStore.swift
  DreamEgg/DreamEgg/Stores/UserSleepConfigStore.swift
  DreamEgg/DreamEgg/Views/Components/GradientBackgroundView.swift
  DreamEgg/DreamEgg/Views/Components/TimePickerView.swift
  DreamEgg/DreamEgg/Views/ContentView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiDreamWorldView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiMainEggView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiMainTabView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiSleepTimeSettingView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiTextCustomView.swift
  DreamEgg/DreamEgg/Views/TestViews/DECalendarTestView.swift
  DreamEgg/DreamEgg/Views/TestViews/SleepTimeSettingView.swift
  DreamEgg/DreamEgg/Views/TestViews/TimePickerTestView.swift
Labels: ✨ Feature

#57 [Feat/#55] Add Haptic feedback for Egg gesture
  DreamEgg/DreamEgg/Stores/EggAnimationStore.swift
Labels: ✨ Feature

#62 Feat/#56 feat 수면 시작 이후 앱에 재 진입한 화면 awakeview을 꾸밉니다
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/Assets.xcassets/EggHat.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/EggHat.imageset/Hat.svg
  DreamEgg/DreamEgg/Assets.xcassets/EggPillow.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/EggPillow.imageset/Pillow.svg
  DreamEgg/DreamEgg/Assets.xcassets/ShinyMiddle.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/ShinyMiddle.imageset/ShinyMiddle.svg
  DreamEgg/DreamEgg/Extensions/View+ActivateConfetti.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiAwakeView.swift
Labels: ✨ Feature

#66 Feat/#58 EggDrawView, EggInteractionView를 그리고 SleepGuideView와 연결합니다.
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/Assets.xcassets/samplePillow.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/samplePillow.imageset/Pillow.svg
  DreamEgg/DreamEgg/Stores/EggAnimationStore.swift
  DreamEgg/DreamEgg/Stores/EggDrawStore.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiEggDrawView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiEggInteractionView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiMainEggView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiSleepGuideView.swift
  DreamEgg/DreamEgg/Views/TestViews/EggInteractionTestView.swift
Labels: ✨ Feature

#59 Feat/#53-Connecting-Logic-to-LofiDreamWorldView
  DreamEgg/DreamEgg/Stores/MapViewStore.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiDreamWorldView.swift
Labels: ✨ Feature

#65 Feat/#60-Add-LofiDreamPetBirthView
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/Views/Lofi/LofiAwakeView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiBirthView.swift
Labels: ✨ Feature

#70 [Feat#67] Sparkle과 Zzz에 Spring Animation을 적용합니다.
  DreamEgg/DreamEgg/Assets.xcassets/ShinySmall.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/ShinySmall.imageset/ShinySmall.svg
  DreamEgg/DreamEgg/Views/Lofi/LofiAwakeView.swift
Labels: ✨ Feature, 🎨 Design

#72 Feat/#69 debutton
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/Views/Components/DEButton.swift
  DreamEgg/DreamEgg/Views/Components/DENavigationLink.swift
Labels: ✨ Feature, 🎨 Design

#80 [Feat/#76] LofiFailedView 작업
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/Views/Lofi/LofiAwakeView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiFailedView.swift
Labels: ✨ Feature

#73 Feat/#71 Add Image Asset & Modifying LofiBirthView Layout
  DreamEgg/DreamEgg/Assets.xcassets/Dreampets/Elephant_Face.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Dreampets/Elephant_Face.imageset/Elephant_Face.svg
  DreamEgg/DreamEgg/Assets.xcassets/Dreampets/Elephant_a.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Dreampets/Elephant_a.imageset/Elephant_a.svg
  DreamEgg/DreamEgg/Assets.xcassets/Dreampets/Elephant_b.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Dreampets/Elephant_b.imageset/Elephant_b.svg
  DreamEgg/DreamEgg/Assets.xcassets/ElephantEgg.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/ElephantEgg.imageset/ElephantEgg.svg
  DreamEgg/DreamEgg/Views/Lofi/LofiBirthView.swift
Labels: ✨ Feature

#84 Feat/#82 update titleanimation of lofiegginteractionview
  DreamEgg/DreamEgg/Views/Lofi/LofiEggInteractionView.swift
Labels: ✨ Feature

#87 [Feat/#74] Make DreamWorldMap FullScreen
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/Assets.xcassets/DreamWorldMap.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/DreamWorldMap.imageset/DreamWorldMap.svg
  DreamEgg/DreamEgg/Stores/MapViewStore.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiDreamWorldView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiMainTabView.swift
Labels: ✨ Feature

#85 [Feat/#83] Modifying LofiCreatureNamingView, LofiNameConfirmView
  DreamEgg/DreamEgg/Views/Lofi/LofiCreatureNamingView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiNameConfirmView.swift
Labels: ✨ Feature

#90 Feat/#86 add lofisleepguideview gesture labeling
  DreamEgg/DreamEgg/Stores/EggAnimationStore.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiEggInteractionView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiSleepGuideView.swift
  DreamEgg/DreamEgg/Views/TestViews/EggInteractionTestView.swift
Labels: ✨ Feature

#63 Feat/#52 local push notification connect
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/DreamEgg.entitlements
  DreamEgg/DreamEgg/DreamEggApp.swift
  DreamEgg/DreamEgg/Info.plist
  DreamEgg/DreamEgg/Models/DENavigationManager.swift
  DreamEgg/DreamEgg/Resources/Constants.swift
  DreamEgg/DreamEgg/Stores/LocalNotificationStore.swift
  DreamEgg/DreamEgg/Stores/UserSleepConfigStore.swift
  DreamEgg/DreamEgg/Views/ContentView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiMainEggView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiSleepGuideView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiSleepTimeSettingView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiTextCustomView.swift
  DreamEgg/DreamEgg/Views/TestViews/LocalNotificationView.swift
Labels: ✨ Feature

#78 Feat/#64 coredata daily sleep crud
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/Assets.xcassets/Dreampets/Rabbit_Face.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Dreampets/Rabbit_Face.imageset/Rabbit_Face.png
  DreamEgg/DreamEgg/Assets.xcassets/Dreampets/Rabbit_b.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Dreampets/Rabbit_b.imageset/Rabbit_b.png
  DreamEgg/DreamEgg/Assets.xcassets/Egg/BinyEgg.imageset/BinyEgg.svg
  DreamEgg/DreamEgg/Assets.xcassets/Egg/BinyEgg.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Egg/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Egg/FerretEgg.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Egg/FerretEgg.imageset/FerretEgg.svg
  DreamEgg/DreamEgg/Assets.xcassets/Egg/emptyEgg.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Egg/emptyEgg.imageset/emptyEgg.svg
  DreamEgg/DreamEgg/DreamEgg.xcdatamodeld/DreamEgg.xcdatamodel/contents
  DreamEgg/DreamEgg/DreamEggApp.swift
  DreamEgg/DreamEgg/Extensions/Date+Utilities.swift
  DreamEgg/DreamEgg/Models/CoreDataContainer.swift
  DreamEgg/DreamEgg/Models/DENavigationManager.swift
  DreamEgg/DreamEgg/Resources/Constants.swift
  DreamEgg/DreamEgg/Stores/ContentViewStore.swift
  DreamEgg/DreamEgg/Stores/CoreDataStore+CRUD.swift
  DreamEgg/DreamEgg/Stores/CoreDataStore.swift
  DreamEgg/DreamEgg/Stores/DailySleepTimeStore.swift
  DreamEgg/DreamEgg/Stores/Interface/CoreDataRepresentable.swift
  DreamEgg/DreamEgg/Stores/LocalNotificationStore.swift
  DreamEgg/DreamEgg/Stores/MapViewStore.swift
  DreamEgg/DreamEgg/Stores/UserSleepConfigStore.swift
  DreamEgg/DreamEgg/Views/Components/DECalendar.swift
  DreamEgg/DreamEgg/Views/ContentView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiAwakeView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiBirthView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiCreatureNamingView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiCurtainView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiDreamWorldView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiMainEggView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiNameConfirmView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiSleepGuideView.swift
  DreamEgg/DreamEgg/Views/TestViews/CoreDataTestView.swift
  DreamEgg/DreamEgg/Views/TestViews/DECalendarTestView.swift
Labels: ✨ Feature

#91 [Feat/#88] Connect Logic to CreatureNamingView & LofiNameConfirmView
  DreamEgg/DreamEgg/Views/Lofi/LofiBirthView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiEggInteractionView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiMainTabView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiNameConfirmView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiSleepGuideView.swift
  DreamEgg/DreamEgg/Views/TestViews/DECalendarTestView.swift
  DreamEgg/DreamEgg/Views/TestViews/EggInteractionTestView.swift
Labels: ✨ Feature

#99 [Feat/#98] Check Code for User Test
  DreamEgg/DreamEgg/Views/Lofi/LofiAwakeView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiBirthView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiEggInteractionView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiNameConfirmView.swift
  DreamEgg/DreamEgg/Views/TestViews/DECalendarTestView.swift
Labels: ✨ Feature

#108 Feat/#104 dailysleep coredata functionally refactor
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/Extensions/Date+Utilities.swift
  DreamEgg/DreamEgg/Extensions/DateComponent+Utilities.swift
  DreamEgg/DreamEgg/Extensions/View+Keyboard.swift
  DreamEgg/DreamEgg/Models/CoreDataContainer.swift
  DreamEgg/DreamEgg/Resources/Constants.swift
  DreamEgg/DreamEgg/Stores/CoreDataStore.swift
  DreamEgg/DreamEgg/Stores/DailySleepTimeStore.swift
  DreamEgg/DreamEgg/Stores/Interface/CoreDataRepresentable.swift
  DreamEgg/DreamEgg/Stores/LocalNotificationStore.swift
  DreamEgg/DreamEgg/Stores/MapViewStore.swift
  DreamEgg/DreamEgg/Stores/UserSleepConfigStore.swift
  DreamEgg/DreamEgg/Views/ContentView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiAwakeView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiBirthView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiCreatureNamingView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiEggDrawView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiEggInteractionView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiMainEggView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiNameConfirmView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiSleepGuideView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiSleepTimeSettingView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiTextCustomView.swift
  DreamEgg/DreamEgg/Views/TestViews/CoreDataTestView.swift
  DreamEgg/DreamEgg/Views/TestViews/CreatureDetailView.swift
  DreamEgg/DreamEgg/Views/TestViews/DECalendarTestView.swift
  DreamEgg/DreamEgg/Views/TestViews/NameEditingView.swift
Labels: ✨ Feature

#103 [Feat/#94] View Transition to DreamWorldView
  DreamEgg/DreamEgg/Views/ContentView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiAwakeView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiFailedView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiMainEggView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiMainTabView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiNameConfirmView.swift
Labels: ✨ Feature

#107 [Feat/#105] LofiSleepGuideView 수면 유도활동에서 버튼 삭제하고 자동으로 넘어가는 라벨 애니메이션 구현하기
  DreamEgg/DreamEgg/Views/Lofi/LofiSleepGuideView.swift
Labels: ✨ Feature
