Repository DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg, pull requests merged in 2023-08, with the labels that each got.

#118 [Feat/#115] Pillow Image 수정
  DreamEgg/DreamEgg/Views/Lofi/LofiEggInteractionView.swift
Labels: 🎨 Design

#120 Feat/#111 coredata time setting to timepicker
  DreamEgg/DreamEgg/Assets.xcassets/Icons/SettingsIcon.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Icons/SettingsIcon.imageset/SettingsIcon.png
  DreamEgg/DreamEgg/Models/DENavigationManager.swift
  DreamEgg/DreamEgg/Stores/TimePickerStore.swift
  DreamEgg/DreamEgg/Views/Components/TimePickerView.swift
  DreamEgg/DreamEgg/Views/ContentView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiAwakeView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiMainEggView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiMainTabView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiSleepTimeSettingView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiTextCustomView.swift
Labels: ✨ Feature

#124 [Feat/#123] DreamPet DreamEgg Assets Added
  DreamEgg/DreamEgg/Assets.xcassets/Dreampets/Dragon_Face.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Dreampets/Dragon_Face.imageset/Dragon_Face.svg
  DreamEgg/DreamEgg/Assets.xcassets/Dreampets/Dragon_a.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Dreampets/Dragon_a.imageset/Dragon_a.svg
  DreamEgg/DreamEgg/Assets.xcassets/Dreampets/Dragon_b.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Dreampets/Dragon_b.imageset/Dragon_b.svg
  DreamEgg/DreamEgg/Assets.xcassets/Egg/BubbleEgg.imageset/BubbleEgg.svg
  DreamEgg/DreamEgg/Assets.xcassets/Egg/BubbleEgg.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Egg/DefaultEgg.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Egg/DefaultEgg.imageset/DefaultEgg.svg
  DreamEgg/DreamEgg/Resources/Constants.swift
Labels: ✨ Feature

#122 Feat/#68 add transition of lofi main egg view
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/Models/DENavigationManager.swift
  DreamEgg/DreamEgg/Views/ContentView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiCreatureNamingView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiEggDrawView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiMainEggView.swift
Labels: ✨ Feature

#125 bug/#121 bugfix coredata dailysleep entity multiple init
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/Assets.xcassets/Egg/ElephantEgg.imageset/Contents.json
  DreamEgg/DreamEgg/Assets.xcassets/Egg/ElephantEgg.imageset/ElephantEgg.svg
  DreamEgg/DreamEgg/Stores/DailySleepTimeStore.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiAwakeView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiBirthView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiDreamWorldView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiFailedView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiMainEggView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiMainTabView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiNameConfirmView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiSleepGuideView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiTextCustomView.swift
  DreamEgg/DreamEgg/Views/TestViews/DECalendarTestView.swift
Labels: bug

#126 Feat/#109 modifting dream world view
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/Models/DENavigationManager.swift
  DreamEgg/DreamEgg/Stores/MapViewStore.swift
  DreamEgg/DreamEgg/Views/ContentView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiAwakeView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiDreamWorldView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiFailedView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiMainTabView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiNameConfirmView.swift
Labels: ✨ Feature

#128 [Feat/#127] feat legibility develop and editing labeling
  DreamEgg/DreamEgg.xcodeproj/project.pbxproj
  DreamEgg/DreamEgg/Assets.xcassets/ClearButton.imageset/ClearButton.svg
  DreamEgg/DreamEgg/Assets.xcassets/ClearButton.imageset/Contents.json
  DreamEgg/DreamEgg/Views/Components/DEFontStyle.swift
  DreamEgg/DreamEgg/Views/Components/DETextField.swift
  DreamEgg/DreamEgg/Views/Components/DETitleHeader.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiAwakeView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiBirthView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiCreatureNamingView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiEggDrawView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiEggInteractionView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiFailedView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiMainEggView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiNameConfirmView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiSleepGuideView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiSleepTimeSettingView.swift
  DreamEgg/DreamEgg/Views/Lofi/LofiTextCustomView.swift
Labels: ✨ Feature
